/**
 * Registro base importado por build-quality-catalog.mjs.
 * ADVERTENCIA: no es la fuente de verdad de la revisión culinaria. Ejecutar
 * build-quality-catalog.mjs (con CONFIRM=1) sobrescribe el trabajo de
 * scripts/culinary-v132-rewrite.mjs y los overrides manuales.
 */

export function buildAllRecipes(h) {
  const { FOD_LOW, FOD_MOD, levels, step, m, ing, recipe, nm, riceBoilSteps } = h;
  const L = levels;
  const out = [];

  const push = (...r) => out.push(...r);

  // —— Familias ——
  function pastaDish(cfg) {
    const pastaG = 80;
    const {
      extraIng,
      sauceSteps,
      pastaNote,
      pastaMin,
      _doneness,
      finishBeginner,
      finishMid,
      finishAdv,
      equipment,
      ingredients,
      ...rest
    } = cfg;
    return recipe({
      ...rest,
      ingredients: ingredients || [
        ing('pasta', `${pastaG} g`, pastaG, 'g'),
        ing('aceite', '1 cucharada', 1, 'cucharada'),
        ing('sal', 'al gusto'),
        ...(extraIng || []),
      ],
      methods: [
        m('olla', 'Olla + sartén', equipment || ['olla', 'vitro', 'sarten'], [
          step(
            'boil-pasta',
            L(
              `En una olla grande con agua hirviendo y sal, cuece ${pastaG} g de pasta ${pastaNote || '9-11 min'}. Para al dente, prueba 1 min antes del fin: debe resistir un poco en el centro. Reserva 2 cucharadas del agua de cocción y escurre.`,
              `Cuece ${pastaG} g de pasta en agua con sal ${pastaNote || '9-11 min'} al dente; reserva 2 cucharadas del agua y escurre.`,
              `Pasta ${pastaG} g al dente; reservar 2 cdas agua de cocción y escurrir.`,
            ),
            { phaseId: 'boil-pasta', timerSeconds: pastaMin ? pastaMin * 60 : 660, timerLabel: 'Pasta', termIds: ['al-dente'] },
          ),
          ...(sauceSteps || []),
          step(
            'finish',
            L(
              finishBeginner,
              finishMid ||
                `${finishBeginner}`.replace(/\s+/g, ' ').slice(0, 160).trim(),
              finishAdv ||
                `${finishBeginner}`.replace(/\s+/g, ' ').slice(0, 100).trim(),
            ),
            { phaseId: 'finish' },
          ),
        ]),
      ],
    });
  }

  function riceDish(cfg) {
    const { riceOpts, ...rest } = cfg;
    return recipe({
      ...rest,
      methods: [
        m('olla', 'Olla', ['olla', 'vitro'], riceBoilSteps(riceOpts)),
      ],
    });
  }

  function sartenProtein(cfg) {
    const protein = nm(cfg.proteinId);
    const cookMin = cfg.cookMin || 8;
    return recipe({
      id: cfg.id,
      name: cfg.name,
      timeMinutes: cfg.timeMinutes,
      difficulty: cfg.difficulty,
      dishRole: cfg.dishRole,
      pepperTags: cfg.pepperTags,
      fodmap: cfg.fodmap || FOD_MOD,
      mealTypes: cfg.mealTypes,
      ingredients: cfg.ingredients,
      methods: [
        m('sarten', 'Sartén', ['sarten', 'vitro'], [
          step(
            'prep',
            L(
              cfg.prepBeginner ||
                `Seca y trocea el ${protein} en piezas uniformes. Calienta una sartén con aceite a fuego medio-alto hasta que brille sin humear.`,
              cfg.prepMid ||
                `Trocea ${protein}; calienta aceite en sartén a fuego medio-alto.`,
              cfg.prepAdv ||
                `${protein} troceado; sartén con aceite a fuego medio-alto.`,
            ),
            { phaseId: 'prep', heatLevel: 'medio-alto' },
          ),
          step(
            'cook',
            L(
              cfg.cookBeginner ||
                `Cocina el ${protein} ${cookMin} min removiendo o volteando según el corte hasta que no quede rosado en el centro (corta un trozo) y los jugos salgan claros. Sirve al momento.`,
              cfg.cookMid ||
                `Cocina ${protein} ${cookMin} min a fuego medio-alto hasta cocinado por dentro; comprueba corte y jugos claros; sirve.`,
              cfg.cookAdv ||
                `Saltea ${protein} ${cookMin} min al punto interior; jugos claros; servir.`,
            ),
            {
              phaseId: 'cook',
              heatLevel: 'medio-alto',
              termIds: cfg.termIds || ['saltear'],
              ...(cfg.timerSeconds
                ? {
                    timerSeconds: cfg.timerSeconds,
                    timerLabel: cfg.timerLabel || protein,
                  }
                : {}),
            },
          ),
          ...(cfg.extraSteps || []),
        ]),
      ],
    });
  }

  function noCook(cfg) {
    const { beginner, intermediate, advanced, step2, ...rest } = cfg;
    return recipe({
      ...rest,
      methods: [
        m('none', 'Sin cocción', [], [
          step('assemble', L(beginner, intermediate, advanced)),
          ...(step2 ? [step('finish', L(step2.b, step2.i, step2.a))] : []),
        ]),
      ],
    });
  }

  function applianceProduct(cfg) {
    const { productDesc, methods: methodDefs, base, ...rest } = cfg;
    const methods = methodDefs.map(([mid, label, eq, tempC, mins, similarKey]) =>
      m(
        mid,
        label,
        eq,
        [
          step(
            'prep',
            L(
              `Dispón ${productDesc} en una sola capa sin amontonar${tempC != null ? `. Precalienta ${label} a ${tempC} °C si el aparato lo indica` : ''}.`,
              `Capa única sin amontonar${tempC != null ? `; ${tempC} °C` : ''}.`,
              `Una capa${tempC != null ? `; ${tempC} °C` : ''}.`,
            ),
            { phaseId: 'prep' },
          ),
          step(
            'cook',
            L(
              `Cocina ${mins} min${tempC ? ` a ${tempC} °C` : ''}; voltea o agita a mitad de tiempo. Por fuera dorado; por dentro bien caliente y cocido (abre uno si dudas).`,
              `${mins} min${tempC ? ` a ${tempC} °C` : ''} con volteo a mitad; dorado por fuera y cocido por dentro.`,
              `${mins} min${tempC ? ` @ ${tempC}°C` : ''}; volteo a mitad hasta dorado y cocido.`,
            ),
            {
              timerSeconds: mins * 60,
              timerLabel: label,
              ...(tempC ? { temperatureC: tempC } : {}),
              ...(similarKey ? { similarKey } : {}),
            },
          ),
          step('serve', L('Sirve al momento en plato caliente.', 'Emplata y sirve.', 'Servir al momento.'), { phaseId: 'serve' }),
        ],
        {
          timeMinutes: mins,
          ...(tempC ? { temperature: `${tempC} °C`, temperatureC: tempC } : {}),
        },
      ),
    );
    return recipe({ ...(base || rest), methods });
  }

  // —— Handcrafted (desde build-quality-catalog) ——
  push(
    h.buildPolloPatatasCombo(),
    h.buildPolloArrozCalabacin(),
    h.buildCalabacinPlancha(),
    h.buildTortillaPatata(),
    h.buildArrozAtun(),
  );

  // —— Huevos / desayuno ——
  push(
    recipe({
      id: 'huevos-fritos-pan',
      name: 'Huevos fritos con pan',
      timeMinutes: 10,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'cena'],
      fodmap: FOD_LOW,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('pan', '2 rebanadas', 2, 'rebanada'), ing('aceite', '2 cucharadas', 2, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro', 'tostadora'], [
        step('toast', L('Tuesta el pan en tostadora o sartén seca hasta crujiente.', 'Tuesta pan.', 'Tostar pan.')),
        step('fry-egg', L('Aceite en sartén a fuego medio: casca los huevos y fríe 2-3 min hasta clara cuajada y yema blanda. Salpica sal.', 'Fríe huevos 2-3 min.', 'Huevos fritos.'), { timerSeconds: 180, timerLabel: 'Huevos' }),
        step('serve', L('Sirve un huevo sobre cada rebanada.', 'Emplata.', 'Sirve.')),
      ])],
    }),
    recipe({
      id: 'tortilla-francesa',
      name: 'Tortilla francesa',
      timeMinutes: 8,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'cena'],
      fodmap: FOD_LOW,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('beat', L('Bate huevos con sal en un bol hasta homogéneo.', 'Bate huevos.', 'Batir.')),
        step('cook', L('Sartén antiadherente con aceite a fuego medio-bajo: vierte huevo, empuja bordes y inclina. Cuaja 2 min, pliega en tercios y sirve.', 'Tortilla francesa 2 min.', 'Tortilla francesa.'), { timerSeconds: 120, timerLabel: 'Tortilla' }),
      ])],
    }),
    recipe({
      id: 'huevos-revueltos-jamon',
      name: 'Huevos revueltos con jamón',
      timeMinutes: 10,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'cena'],
      fodmap: FOD_MOD,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('jamon', '2 lonchas', 2, 'loncha'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('prep', L('Trocea el jamón. Bate los huevos con sal.', 'Jamón troceado; huevo batido.', 'Prep.')),
        step('scramble', L('Sartén con aceite a fuego bajo: añade jamón 30 s, vierte huevo y remueve suave 2-3 min hasta cuajado cremoso.', 'Revuelve a fuego bajo 2-3 min.', 'Revuelto.'), { timerSeconds: 180, timerLabel: 'Revuelto' }),
      ])],
    }),
    recipe({
      id: 'omelette-queso',
      name: 'Omelette de queso',
      timeMinutes: 10,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'cena'],
      fodmap: FOD_MOD,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('queso', '40 g', 40, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('prep', L('Ralla o trocea el queso. Bate huevos con sal.', 'Queso + huevo batido.', 'Prep.')),
        step('cook', L('Sartén con aceite a fuego medio: huevo, cuando cuaje base espolvorea queso, pliega por la mitad 1-2 min.', 'Omelette con queso 2 min.', 'Omelette queso.'), { timerSeconds: 120, timerLabel: 'Omelette' }),
      ])],
    }),
    recipe({
      id: 'omelette-espinacas',
      name: 'Omelette de espinacas',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['desayuno', 'cena'],
      fodmap: FOD_MOD,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('espinacas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('wilt', L('Saltea espinacas en sartén con un poco de aceite 1-2 min hasta que mengüen. Escurre líquido.', 'Saltea espinacas 1-2 min.', 'Esp. salteadas.'), { termIds: ['saltear'], timerSeconds: 120, timerLabel: 'Espinacas' }),
        step('omelette', L('Bate huevos, vierte sobre espinacas a fuego medio-bajo, pliega cuando cuaje 3 min.', 'Omelette espinacas 3 min.', 'Omelette.'), { timerSeconds: 180, timerLabel: 'Omelette' }),
      ])],
    }),
    recipe({
      id: 'huevo-micro',
      name: 'Huevo al microondas',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      fodmap: FOD_LOW,
      ingredients: [ing('huevos', '1 unidad', 1, 'unidad')],
      methods: [m('micro', 'Microondas', ['microondas'], [
        step('cook', L('Rompe el huevo en un bol apto micro, pincha yema 2 veces, tapa parcialmente. Potencia media 45-60 s; reposa 30 s. Clara cuajada.', 'Micro 45-60 s.', 'Micro huevo.'), { timerSeconds: 60, timerLabel: 'Huevo micro', termIds: ['reposar'] }),
      ])],
    }),
    recipe({
      id: 'avena-leche-micro',
      name: 'Avena con leche',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno'],
      fodmap: FOD_MOD,
      ingredients: [ing('avena', '40 g', 40, 'g'), ing('leche', '200 ml', 200, 'ml')],
      methods: [m('micro', 'Microondas', ['microondas'], [
        step('cook', L('Mezcla avena y leche en bol alto. Microondas media potencia 2 min, remueve, otros 1 min hasta espesar.', 'Micro 2+1 min removiendo.', 'Porridge micro.'), { timerSeconds: 180, timerLabel: 'Avena' }),
      ])],
    }),
    noCook({
      id: 'avena-leche-fria',
      name: 'Avena con leche fría',
      timeMinutes: 3,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('avena', '40 g', 40, 'g'), ing('leche', '150 ml', 150, 'ml')],
      beginner: 'Mezcla avena y leche fría en un bol; deja 2 min para hidratar y come.',
      intermediate: 'Avena + leche fría; reposar 2 min.',
      advanced: 'Overnight style rápido.',
    }),
    noCook({
      id: 'yogur-fresas',
      name: 'Yogur con fresas',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('yogur', '1 unidad', 1, 'unidad'), ing('fresas', '1 puñado', 1, 'puñado')],
      beginner: 'Lava fresas, córtalas en rodajas y mézclalas con el yogur en un bol.',
      intermediate: 'Yogur con fresas troceadas.',
      advanced: 'Yogur + fresas.',
    }),
    noCook({
      id: 'manzana-yogur',
      name: 'Manzana con yogur',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('manzana', '1 unidad', 1, 'unidad'), ing('yogur', '1 unidad', 1, 'unidad')],
      beginner: 'Corta la manzana en cubos y sirve con yogur encima o mezclado.',
      intermediate: 'Manzana cubos + yogur.',
      advanced: 'Manzana + yogur.',
    }),
    noCook({
      id: 'yogur-platano-avena',
      name: 'Bowl de yogur, plátano y avena',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('yogur', '1 unidad', 1, 'unidad'), ing('platano', '1/2 unidad', 0.5, 'unidad'), ing('avena', '2 cucharadas', 2, 'cucharada')],
      beginner: 'Corta plátano en rodajas. En un bol: yogur, plátano y espolvorea avena.',
      intermediate: 'Bowl yogur, plátano, avena.',
      advanced: 'Bowl desayuno.',
    }),
    noCook({
      id: 'yogur-miel-estilo',
      name: 'Yogur con plátano',
      timeMinutes: 3,
      difficulty: 'fácil',
      dishRole: 'desayuno',
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('yogur', '1 unidad', 1, 'unidad'), ing('platano', '1/2 unidad', 0.5, 'unidad')],
      beginner: 'Machaca o corta medio plátano y mezcla con yogur.',
      intermediate: 'Yogur + plátano.',
      advanced: 'Yogur plátano.',
    }),
    noCook({
      id: 'naranja-fresca',
      name: 'Naranja fresca',
      timeMinutes: 3,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_LOW,
      ingredients: [ing('naranja', '1 unidad', 1, 'unidad')],
      beginner: 'Pela la naranja en gajos o córtala en rodajas y come.',
      intermediate: 'Pelar y servir naranja.',
      advanced: 'Naranja fresca.',
    }),
  );

  // —— Tostadas / bocadillos ——
  const toastStep = () =>
    step('toast', L(
      'Tuesta el pan en tostadora o sartén seca hasta dorado y crujiente por fuera, sin quemar los bordes.',
      'Tuesta el pan hasta dorado uniforme y crujiente.',
      'Pan tostado dorado y crujiente, sin quemar.',
    ), { phaseId: 'toast' });

  const toast = (id, name, foods, topSteps, diff = 'fácil', role = 'snack', tags = ['rapido'], meals = ['desayuno', 'merienda']) =>
    recipe({
      id,
      name,
      timeMinutes: 8,
      difficulty: diff,
      dishRole: role,
      pepperTags: tags,
      mealTypes: meals,
      fodmap: FOD_MOD,
      ingredients: foods,
      methods: [m('tostadora', 'Tostadora', ['tostadora'], [toastStep(), ...topSteps])],
    });

  push(
    toast('tostada-tomate-queso', 'Tostada de tomate y queso', [ing('pan', '2 rebanadas', 2, 'rebanada'), ing('tomate', '1/2 unidad', 0.5, 'unidad'), ing('queso', '2 lonchas', 2, 'loncha')], [
      step('top', L(
        'Ralla o corta tomate fino, colócalo sobre pan caliente y cubre con queso. Opcional: gratinar 1 min en sartén tapada hasta que el queso se derrita.',
        'Tomate y queso sobre pan caliente; gratinar 1 min si quieres queso fundido.',
        'Tomate + queso en tostada caliente; gratinar opcional 1 min.',
      ), { phaseId: 'top', timerSeconds: 60, timerLabel: 'Gratinar queso', termIds: ['gratinar'] }),
    ], 'fácil', 'desayuno'),
    toast('tostada-atun', 'Tostada de atún y tomate', [ing('pan', '2 rebanadas', 2, 'rebanada'), ing('atun', '1/2 lata', 0.5, 'lata'), ing('tomate', '1/2 unidad', 0.5, 'unidad')], [
      step('top', L(
        'Escurre el atún, mezcla con tomate troceado y extiende sobre las tostadas calientes.',
        'Atún escurrido con tomate sobre pan tostado.',
        'Montar atún y tomate en tostada caliente.',
      ), { phaseId: 'top' }),
    ]),
    toast('tostada-platano-queso', 'Tostada de plátano y queso', [ing('pan', '2 rebanadas', 2, 'rebanada'), ing('platano', '1/2 unidad', 0.5, 'unidad'), ing('queso', '1 loncha', 1, 'loncha')], [
      step('top', L(
        'Coloca rodajas finas de plátano y queso encima del pan caliente; come templado.',
        'Plátano y queso sobre tostada caliente.',
        'Montar plátano + queso en pan tostado.',
      ), { phaseId: 'top' }),
    ], 'fácil', 'desayuno'),
    toast('tostada-pavo', 'Tostada de pavo', [ing('pan', '2 rebanadas', 2, 'rebanada'), ing('pavo', '2 lonchas', 2, 'loncha')], [
      step('top', L(
        'Coloca lonchas de pavo sobre el pan caliente y sirve al momento.',
        'Pavo sobre tostada caliente; servir.',
        'Lonchas de pavo en pan tostado.',
      ), { phaseId: 'top' }),
    ], 'fácil', 'snack', ['rapido'], ['merienda', 'cena']),
    toast('tostada-jamon', 'Tostada de jamón', [ing('pan', '2 rebanadas', 2, 'rebanada'), ing('jamon', '2 lonchas', 2, 'loncha')], [
      step('top', L(
        'Coloca el jamón sobre el pan caliente y sirve al momento.',
        'Jamón sobre tostada caliente; servir.',
        'Jamón en pan tostado caliente.',
      ), { phaseId: 'top' }),
    ]),
    recipe({
      id: 'tostada-huevo-tomate',
      name: 'Tostada con huevo y tomate',
      timeMinutes: 10,
      difficulty: 'media',
      dishRole: 'desayuno',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('pan', '2 rebanadas', 2, 'rebanada'), ing('huevos', '2 unidades', 2, 'unidad'), ing('tomate', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Tostadora + sartén', ['tostadora', 'sarten', 'vitro'], [
        step('parallel', L(
          'Tuesta el pan. En sartén con aceite a fuego medio fríe los huevos 2-3 min hasta clara cuajada. Corta tomate en rodajas.',
          'Tuesta pan; fríe huevos 2-3 min; tomate en rodajas.',
          'Pan tostado, huevo frito 2-3 min y tomate en rodajas listos.',
        ), { phaseId: 'prep' }),
        step('serve', L(
          'Coloca tomate sobre el pan, encima el huevo frito; salpica sal y sirve al momento.',
          'Monta tostada con tomate y huevo; sal y servir.',
          'Emplatar tostada tomate-huevo con sal.',
        ), { phaseId: 'serve' }),
      ])],
    }),
    noCook({
      id: 'bocadillo-pavo',
      name: 'Bocadillo de pavo y queso',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido'],
      mealTypes: ['comida', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('pan', '1 bollo', 1, 'unidad'), ing('pavo', '2 lonchas', 2, 'loncha'), ing('queso', '1 loncha', 1, 'loncha')],
      beginner: 'Abre el pan, coloca pavo y queso; cierra y corta si quieres.',
      intermediate: 'Bocadillo pavo + queso.',
      advanced: 'Montar bocadillo.',
    }),
    noCook({
      id: 'bocadillo-jamon-tomate',
      name: 'Bocadillo de jamón y tomate',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido'],
      mealTypes: ['comida', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('pan', '1 bollo', 1, 'unidad'), ing('jamon', '2 lonchas', 2, 'loncha'), ing('tomate', '2 rodajas', 2, 'rodaja')],
      beginner: 'Pan, jamón y rodajas de tomate; opcional un hilo de aceite.',
      intermediate: 'Bocadillo jamón y tomate.',
      advanced: 'Montar.',
    }),
    noCook({
      id: 'hummus-pan',
      name: 'Hummus con pan',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['merienda', 'cena'],
      fodmap: FOD_MOD,
      ingredients: [ing('hummus', '3 cucharadas', 3, 'cucharada'), ing('pan', '2 rebanadas', 2, 'rebanada')],
      beginner: 'Unta hummus generoso en pan o usa pan para mojar.',
      intermediate: 'Hummus + pan.',
      advanced: 'Servir.',
    }),
    noCook({
      id: 'wrap-pavo-queso',
      name: 'Wrap de pavo y queso',
      timeMinutes: 10,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido'],
      mealTypes: ['comida', 'merienda', 'cena'],
      fodmap: FOD_MOD,
      ingredients: [ing('tortillas-trigo', '1 unidad', 1, 'unidad'), ing('pavo', '2 lonchas', 2, 'loncha'), ing('queso', '1 loncha', 1, 'loncha')],
      beginner: 'Calienta la tortilla 15 s en sartén seca. Rellena con pavo y queso, enrolla apretando bordes.',
      intermediate: 'Wrap pavo y queso.',
      advanced: 'Enrollar wrap.',
    }),
    noCook({
      id: 'pan-tomate-aceite',
      name: 'Pan con tomate',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido'],
      mealTypes: ['desayuno', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('pan', '2 rebanadas', 2, 'rebanada'), ing('tomate', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      beginner: 'Tuesta pan si quieres, frota tomate y añade aceite y sal.',
      intermediate: 'Pan con tomate y aceite.',
      advanced: 'Pan tomate.',
    }),
    noCook({
      id: 'queso-aceitunas',
      name: 'Queso con aceitunas',
      timeMinutes: 3,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido'],
      mealTypes: ['merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('queso', '50 g', 50, 'g'), ing('aceitunas', '1 puñado', 1, 'puñado')],
      beginner: 'Corta queso en cubos y sirve con aceitunas escurridas.',
      intermediate: 'Tabla queso y aceitunas.',
      advanced: 'Servir.',
    }),
    noCook({
      id: 'rollito-pavo',
      name: 'Rollito de pavo y lechuga',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'entrante',
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['merienda', 'cena'],
      fodmap: FOD_LOW,
      ingredients: [ing('pavo', '2 lonchas', 2, 'loncha'), ing('lechuga', '2 hojas', 2, 'hoja')],
      beginner: 'Enrolla lonchas de pavo con hojas de lechuga crujiente.',
      intermediate: 'Rollitos pavo-lechuga.',
      advanced: 'Montar.',
    }),
    noCook({
      id: 'jamon-melon-estilo',
      name: 'Jamón con tomate',
      timeMinutes: 5,
      difficulty: 'fácil',
      dishRole: 'entrante',
      pepperTags: ['rapido'],
      mealTypes: ['merienda'],
      fodmap: FOD_MOD,
      ingredients: [ing('jamon', '2 lonchas', 2, 'loncha'), ing('tomate', '1/2 unidad', 0.5, 'unidad')],
      beginner: 'Corta tomate en gajos y enróllalo con jamón.',
      intermediate: 'Jamón + tomate.',
      advanced: 'Montar.',
    }),
  );

  // —— Ensaladas ——
  const salad = (id, name, ings, prepB, diff = 'fácil', role = 'entrante') =>
    recipe({
      id,
      name,
      timeMinutes: 10,
      difficulty: diff,
      dishRole: role,
      pepperTags: ['rapido', 'ligero'],
      mealTypes: ['comida', 'cena', 'merienda'],
      fodmap: FOD_MOD,
      ingredients: ings,
      methods: [m('none', 'Sin cocción', [], [
        step('prep', L(
          prepB,
          `${prepB}`.split('.').slice(0, 2).join('.').trim() + (prepB.includes('.') ? '.' : ''),
          `${prepB}`.replace(/\s+/g, ' ').slice(0, 120).trim(),
        ), { phaseId: 'prep' }),
        step('dress', L(
          'Aliña con aceite y sal justo antes de comer para que la lechuga no se ablande.',
          'Aceite y sal al final; mezcla y sirve.',
          'Aliñar al momento y servir.',
        ), { phaseId: 'dress' }),
      ])],
    });

  push(
    salad('ensalada-atun', 'Ensalada de atún', [ing('atun', '1 lata', 1, 'lata'), ing('lechuga', '1/2 unidad', 0.5, 'unidad'), ing('tomate', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')], 'Escurre atún. Lava lechuga y tomate, trocea y mezcla en bol.'),
    salad('ensalada-tomate-pepino', 'Ensalada de tomate y pepino', [ing('tomate', '2 unidades', 2, 'unidad'), ing('pepino', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')], 'Corta tomate en gajos y pepino en medias lunas finas.'),
    salad('maiz-atun', 'Ensalada de maíz y atún', [ing('maiz', '1/2 lata', 0.5, 'lata'), ing('atun', '1/2 lata', 0.5, 'lata'), ing('lechuga', 'hojas', 1, 'puñado')], 'Escurre maíz y atún; mezcla con lechuga troceada.'),
    salad('ensalada-garbanzos', 'Ensalada de garbanzos', [ing('garbanzos', '1/2 lata', 0.5, 'lata'), ing('tomate', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')], 'Escurre garbanzos, añade tomate en cubos.'),
    salad('ensalada-maiz-tomate', 'Ensalada de maíz y tomate', [ing('maiz', '1/2 lata', 0.5, 'lata'), ing('tomate', '1 unidad', 1, 'unidad'), ing('lechuga', 'hojas', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada')], 'Mezcla maíz escurrido, tomate y lechuga.'),
    salad('ensalada-pepino-atun', 'Ensalada de pepino y atún', [ing('pepino', '1/2 unidad', 0.5, 'unidad'), ing('atun', '1/2 lata', 0.5, 'lata'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')], 'Pepino en rodajas finas y atún escurrido.'),
    salad('ensalada-lechuga-maiz', 'Ensalada de lechuga y maíz', [ing('lechuga', '1/2 unidad', 0.5, 'unidad'), ing('maiz', '1/2 lata', 0.5, 'lata'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')], 'Lava y trocea la lechuga; escurre el maíz y mezcla ambos en un bol.'),
  );

  // —— Pasta ——
  push(
    pastaDish({
      id: 'pasta-atun-tomate',
      name: 'Pasta con atún y tomate',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'completo'],
      fodmap: FOD_MOD,
      extraIng: [ing('atun', '1 lata', 1, 'lata'), ing('tomate-frito', '100 g', 100, 'g')],
      sauceSteps: [
        step('sauce', L('En sartén calienta tomate frito 2 min. Escurre atún y añade sin cocinar mucho.', 'Tomate frito + atún.', 'Salsa atún.'), { termIds: ['sofreir'], timerSeconds: 120, timerLabel: 'Salsa' }),
      ],
      finishBeginner: 'Mezcla pasta escurrida con la salsa; si está seca, un poco de agua de cocción.',
      finishMid: 'Integrar pasta y salsa.',
      finishAdv: 'Emplatar.',
    }),
    pastaDish({
      id: 'pasta-atun-simple',
      name: 'Pasta con atún',
      timeMinutes: 12,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      extraIng: [ing('atun', '1 lata', 1, 'lata')],
      equipment: ['olla', 'vitro'],
      sauceSteps: [],
      finishBeginner: 'Escurre atún, mezcla con pasta caliente, aceite y sal fuera del fuego.',
      finishMid: 'Pasta + atún + aceite.',
      finishAdv: 'Mezclar.',
    }),
    pastaDish({
      id: 'pasta-queso-espinacas',
      name: 'Pasta con queso y espinacas',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'comfort'],
      fodmap: FOD_MOD,
      extraIng: [ing('queso', '50 g', 50, 'g'), ing('espinacas', '1 puñado', 1, 'puñado')],
      equipment: ['olla', 'vitro', 'sarten'],
      sauceSteps: [
        step('veg', L('Saltea espinacas 1 min en sartén con aceite hasta menguar.', 'Esp. 1 min.', 'Esp.'), { termIds: ['saltear'], timerSeconds: 60, timerLabel: 'Espinacas' }),
      ],
      finishBeginner: 'Mezcla pasta con espinacas y queso rallado; el calor derrite el queso.',
      finishMid: 'Pasta, espinacas, queso.',
      finishAdv: 'Mezclar.',
    }),
    pastaDish({
      id: 'pasta-ajo-aceite',
      name: 'Pasta con ajo y aceite',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      extraIng: [ing('ajo', '2 dientes', 2, 'diente')],
      sauceSteps: [
        step('garlic-oil', L(
          'En sartén, aceite frío con ajo laminado a fuego muy bajo 2 min removiendo hasta dorado claro, sin quemar.',
          'Sofríe ajo laminado en aceite frío a fuego muy bajo 2 min, dorado claro sin quemar.',
          'Ajo en aceite frío, fuego muy bajo 2 min hasta dorado claro.',
        ), { phaseId: 'garlic-oil', termIds: ['sofreir'], timerSeconds: 120, timerLabel: 'Ajo', heatLevel: 'bajo' }),
      ],
      finishBeginner: 'Vierte pasta escurrida en la sartén del ajo, mezcla con un chorrito de agua de cocción si hace falta y sirve.',
      finishMid: 'Pasta escurrida a la sartén del ajo; ligar con agua de cocción si está seca; servir.',
      finishAdv: 'Integrar pasta con ajo y aceite; hidratar con agua de cocción si hace falta; servir.',
    }),
    pastaDish({
      id: 'pasta-tomate-simple',
      name: 'Pasta con tomate frito',
      timeMinutes: 15,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'comfort'],
      fodmap: FOD_MOD,
      extraIng: [ing('tomate-frito', '150 g', 150, 'g')],
      equipment: ['olla', 'vitro', 'sarten'],
      sauceSteps: [
        step('sauce', L('Calienta tomate frito en sartén 3 min removiendo.', 'Tomate frito 3 min.', 'Salsa.'), { timerSeconds: 180, timerLabel: 'Tomate' }),
      ],
      finishBeginner: 'Mezcla pasta escurrida con la salsa caliente hasta cubrir; sirve al momento.',
      finishMid: 'Integra pasta escurrida con salsa caliente y sirve.',
      finishAdv: 'Ligar pasta con salsa caliente y servir al momento.',
    }),
    pastaDish({
      id: 'pasta-brocoli',
      name: 'Pasta con brócoli',
      timeMinutes: 18,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'ligero'],
      fodmap: FOD_MOD,
      extraIng: [ing('brocoli', '1/2 unidad', 0.5, 'unidad')],
      sauceSteps: [
        step('broccoli', L('Cuece brócoli troceado en la misma olla 4 min antes de sacar pasta; o blanquea aparte.', 'Brócoli 4 min.', 'Brócoli.'), { termIds: ['blanquear'], timerSeconds: 240, timerLabel: 'Brócoli' }),
      ],
      finishBeginner: 'Mezcla pasta y brócoli con aceite y sal.',
      finishMid: 'Pasta brócoli.',
      finishAdv: 'Mezclar.',
    }),
    pastaDish({
      id: 'pasta-maiz-atun',
      name: 'Pasta con maíz y atún',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      extraIng: [ing('maiz', '1/2 lata', 0.5, 'lata'), ing('atun', '1/2 lata', 0.5, 'lata')],
      equipment: ['olla', 'vitro'],
      finishBeginner: 'Escurre maíz y atún; mezcla con pasta caliente y aceite.',
      finishMid: 'Pasta + maíz + atún.',
      finishAdv: 'Mezclar.',
    }),
    pastaDish({
      id: 'pasta-pavo',
      name: 'Pasta con pavo salteado',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      extraIng: [ing('pavo', '100 g', 100, 'g')],
      sauceSteps: [
        step('pavo', L('Saltea tiras de pavo en sartén 4-5 min hasta cocinado.', 'Pavo 4-5 min.', 'Pavo.'), { termIds: ['saltear'], timerSeconds: 300, timerLabel: 'Pavo' }),
      ],
      finishBeginner: 'Mezcla pasta con pavo y un chorrito de aceite.',
      finishMid: 'Integrar pasta y pavo.',
      finishAdv: 'Servir.',
    }),
  );

  // —— Arroz (más platos) ——
  push(
    riceDish({
      id: 'arroz-tomate',
      name: 'Arroz con tomate frito',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['comfort'],
      fodmap: FOD_MOD,
      ingredients: [ing('arroz', '80 g', 80, 'g'), ing('tomate-frito', '100 g', 100, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      riceOpts: {
        addinLine: 'Ten tomate frito listo.',
        mixStep: step('mix', L('Tras reposar arroz, incorpora tomate frito calentado en sartén 2 min y mezcla.', 'Tomate frito + arroz.', 'Mezclar.'), { timerSeconds: 120, timerLabel: 'Tomate' }),
        finishStep: step('serve', L(
          'Prueba sal y sirve el arroz caliente en un plato hondo.',
          'Ajusta sal y emplata el arroz caliente.',
          'Servir arroz caliente emplatado.',
        ), { phaseId: 'serve' }),
      },
    }),
    riceDish({
      id: 'arroz-garbanzos',
      name: 'Arroz con garbanzos',
      timeMinutes: 25,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'comfort'],
      fodmap: FOD_MOD,
      ingredients: [ing('arroz', '80 g', 80, 'g'), ing('garbanzos', '1/2 lata', 0.5, 'lata'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      riceOpts: {
        addinLine: 'Escurre garbanzos.',
        mixStep: step('mix', L('Mezcla garbanzos escurridos con arroz cocido y aceite.', 'Arroz + garbanzos.', 'Mezclar.')),
        finishStep: step('serve', L(
          'Sirve el arroz con garbanzos caliente en un plato hondo.',
          'Emplata arroz y garbanzos calientes.',
          'Servir arroz con garbanzos caliente.',
        ), { phaseId: 'serve' }),
      },
    }),
    recipe({
      id: 'arroz-verduras-huevo',
      name: 'Arroz salteado con verduras y huevo',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('arroz', '80 g', 80, 'g'), ing('huevos', '1 unidad', 1, 'unidad'), ing('zanahoria', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Olla + sartén', ['olla', 'sarten', 'vitro'], [
        ...riceBoilSteps({}),
        step('veg-egg', L('Saltea zanahoria en cubos 4 min; empuja a un lado, casca huevo y revuelve 1 min. Mezcla con arroz.', 'Zanahoria + huevo; mezclar arroz.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 300, timerLabel: 'Salteado' }),
      ])],
    }),
    recipe({
      id: 'arroz-verduras-mixtas',
      name: 'Arroz con verduras mixtas',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('arroz', '80 g', 80, 'g'), ing('verduras-mixtas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Olla + sartén', ['olla', 'sarten', 'vitro'], [
        ...riceBoilSteps({ addinLine: 'Descongela verduras si hace falta.' }),
        step('veg', L('Saltea verduras mixtas 5 min, incorpora arroz y mezcla 1 min.', 'Verduras + arroz.', 'Integrar.'), { termIds: ['saltear'], timerSeconds: 300, timerLabel: 'Verduras' }),
      ])],
    }),
    recipe({
      id: 'arroz-huevo-simple',
      name: 'Arroz con huevo frito',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'comfort'],
      fodmap: FOD_MOD,
      ingredients: [ing('arroz', '80 g', 80, 'g'), ing('huevos', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Olla + sartén', ['olla', 'sarten', 'vitro'], [
        ...riceBoilSteps({}),
        step('egg', L('Fríe huevo en sartén 2-3 min. Sirve sobre arroz.', 'Huevo frito sobre arroz.', 'Emplatar.'), { timerSeconds: 180, timerLabel: 'Huevo' }),
      ])],
    }),
    recipe({
      id: 'arroz-pollo-curry-suave',
      name: 'Arroz con pollo suave',
      timeMinutes: 30,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'completo'],
      fodmap: FOD_LOW,
      ingredients: [ing('arroz', '80 g', 80, 'g'), ing('pollo', '180 g', 180, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Olla + sartén', ['olla', 'sarten', 'vitro'], [
        ...riceBoilSteps({ addinLine: 'Corta pollo en dados.' }),
        step('chicken', L('Saltea pollo en sartén 8 min hasta cocinado. Mezcla con arroz.', 'Pollo + arroz.', 'Integrar.'), { termIds: ['saltear'], timerSeconds: 480, timerLabel: 'Pollo' }),
      ])],
    }),
    recipe({
      id: 'pollo-arroz',
      name: 'Pollo con arroz blanco',
      timeMinutes: 25,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_LOW,
      ingredients: [ing('pollo', '180 g', 180, 'g'), ing('arroz', '80 g', 80, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Olla + sartén', ['sarten', 'olla', 'vitro'], [
        ...riceBoilSteps({ addinLine: 'Sazona pollo.' }),
        step('chicken', L('Saltea pollo 8 min. Sirve junto a arroz o mezcla.', 'Pollo + arroz blanco.', 'Emplatar.'), { termIds: ['saltear'], timerSeconds: 480, timerLabel: 'Pollo' }),
      ])],
    }),
    recipe({
      id: 'bowl-arroz-salmon',
      name: 'Bowl de arroz y salmón',
      timeMinutes: 25,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'completo'],
      fodmap: FOD_LOW,
      ingredients: [ing('arroz', '80 g', 80, 'g'), ing('salmon', '150 g', 150, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Olla + sartén', ['olla', 'sarten', 'vitro'], [
        ...riceBoilSteps({}),
        step('salmon', L(
          'Seca el salmón. Sartén con aceite a fuego medio-alto: cocina 3-4 min por lado hasta opaco por fuera y que se separe en lascas; centro aún jugoso.',
          'Sella salmón 3-4 min por lado a fuego medio-alto hasta opaco y lascas fáciles; centro jugoso.',
          'Salmón 3-4 min/lado hasta opaco; lascas fáciles; centro jugoso.',
        ), { phaseId: 'cook-salmon', termIds: ['sellar'], timerSeconds: 420, timerLabel: 'Salmón', heatLevel: 'medio-alto' }),
        step('bowl', L(
          'Pon arroz en un bol, coloca el salmón encima y sirve al momento.',
          'Arroz en bol con salmón encima; servir.',
          'Emplatar bowl arroz y salmón.',
        ), { phaseId: 'serve' }),
      ])],
    }),
  );

  // —— Proteínas / salteados ——
  push(
    sartenProtein({
      id: 'pollo-pimiento',
      name: 'Salteado de pollo y pimiento',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      proteinId: 'pollo',
      ingredients: [ing('pollo', '180 g', 180, 'g'), ing('pimiento', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      prepBeginner: 'Corta pollo y pimiento en tiras. Sartén con aceite a fuego alto.',
      cookBeginner: 'Saltea pollo 5 min, añade pimiento 4 min hasta tierno y pollo hecho.',
      cookMin: 9,
      timerSeconds: 540,
      timerLabel: 'Salteado',
    }),
    sartenProtein({
      id: 'pollo-ajos',
      name: 'Pollo al ajillo sencillo',
      timeMinutes: 25,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'completo'],
      fodmap: FOD_LOW,
      proteinId: 'pollo',
      ingredients: [ing('pollo', '180 g', 180, 'g'), ing('ajo', '3 dientes', 3, 'diente'), ing('aceite', '2 cucharadas', 2, 'cucharada'), ing('sal', 'al gusto')],
      prepBeginner: 'Trocea el pollo. Pela y lamina el ajo.',
      prepMid: 'Trocea pollo; lamina ajo.',
      prepAdv: 'Pollo en dados; ajo laminado.',
      cookBeginner: 'Sofríe el ajo sin quemar a fuego medio; saltea el pollo 8-10 min a fuego medio-alto hasta cocinado. Sirve con el ajo.',
      cookMid: 'Sofríe ajo; saltea pollo 8-10 min al punto; sirve.',
      cookAdv: 'Ajo sofrito; saltear pollo 8-10 min; servir.',
      cookMin: 10,
      timerSeconds: 600,
      timerLabel: 'Pollo',
      termIds: ['sofreir', 'saltear'],
    }),
    sartenProtein({
      id: 'pollo-limon-sarten',
      name: 'Pollo al limón',
      timeMinutes: 25,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'completo'],
      fodmap: FOD_LOW,
      proteinId: 'pollo',
      ingredients: [ing('pollo', '180 g', 180, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      cookBeginner: 'Saltea pollo 8 min; al final un chorrito de limón si tienes (opcional).',
      timerSeconds: 480,
      timerLabel: 'Pollo',
    }),
    recipe({
      id: 'pollo-plancha-ensalada',
      name: 'Pollo a la plancha con ensalada',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'ligero'],
      fodmap: FOD_LOW,
      ingredients: [ing('pollo', '180 g', 180, 'g'), ing('lechuga', '1/2 unidad', 0.5, 'unidad'), ing('tomate', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [
        m('plancha', 'Plancha', ['plancha', 'vitro'], [
          step('salad', L('Lava lechuga y tomate; reserva ensalada sin aliñar.', 'Ensalada cruda aparte.', 'Prep ensalada.')),
          step('chicken', L('Plancha pollo 5-6 min por lado hasta hecho.', 'Pollo plancha.', 'Plancha pollo.'), { termIds: ['sellar'], timerSeconds: 660, timerLabel: 'Pollo' }),
          step('serve', L('Aliña ensalada al final; sirve con pollo.', 'Emplata pollo + ensalada.', 'Sirve.')),
        ]),
      ],
    }),
    recipe({
      id: 'salmon-verduras',
      name: 'Salmón con verduras',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'completo'],
      fodmap: FOD_LOW,
      ingredients: [ing('salmon', '150 g', 150, 'g'), ing('calabacin', '1/2 unidad', 0.5, 'unidad'), ing('zanahoria', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('veg', L('Saltea calabacín y zanahoria en cubos 6 min.', 'Verduras 6 min.', 'Verduras.'), { termIds: ['saltear'], timerSeconds: 360, timerLabel: 'Verduras' }),
        step('salmon', L('Empuja verduras, sella salmón 3-4 min por lado.', 'Salmón 3-4 min/lado.', 'Salmón.'), { termIds: ['sellar'], timerSeconds: 420, timerLabel: 'Salmón' }),
        step('serve', L('Sirve salmón con verduras.', 'Emplata.', 'Sirve.')),
      ])],
    }),
    sartenProtein({
      id: 'ternera-plancha',
      name: 'Ternera a la plancha',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial'],
      fodmap: FOD_LOW,
      proteinId: 'ternera',
      ingredients: [ing('ternera', '180 g', 180, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      prepBeginner: 'Saca ternera del frío 5 min si puedes. Seca la carne y calienta plancha o sartén con aceite a fuego alto.',
      prepMid: 'Atempera ternera; seca; aceite en plancha muy caliente.',
      prepAdv: 'Ternera seca; plancha caliente con aceite.',
      cookBeginner: 'Cocina 2-3 min por lado según grosor hasta dorado por fuera y rosado medio-jugoso en el centro; reposa 2 min antes de cortar.',
      cookMid: 'Plancha ternera 2-3 min/lado según grosor; reposa 2 min antes de cortar.',
      cookAdv: 'Ternera 2-3 min/lado al punto; reposar 2 min y servir.',
      cookMin: 5,
      termIds: ['sellar', 'reposar'],
      timerSeconds: 180,
      timerLabel: 'Ternera',
    }),
    recipe({
      id: 'ternera-cebolla',
      name: 'Ternera encebollada sencilla',
      timeMinutes: 25,
      difficulty: 'avanzada',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'comfort'],
      fodmap: FOD_MOD,
      ingredients: [ing('ternera', '180 g', 180, 'g'), ing('cebolla', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('onion', L('Cebolla en juliana a fuego medio 8 min hasta blanda.', 'Sofrito cebolla 8 min.', 'Cebolla.'), { termIds: ['sofreir'], timerSeconds: 480, timerLabel: 'Cebolla' }),
        step('beef', L('Sube fuego, añade ternera en tiras 4-5 min removiendo.', 'Ternera 4-5 min.', 'Ternera.'), { termIds: ['saltear'], timerSeconds: 300, timerLabel: 'Ternera' }),
      ])],
    }),
    sartenProtein({
      id: 'pavo-plancha',
      name: 'Pavo a la plancha',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'ligero'],
      fodmap: FOD_LOW,
      proteinId: 'pavo',
      ingredients: [ing('pavo', '120 g', 120, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      cookBeginner: 'Plancha lonchas de pavo 2-3 min por lado.',
      timerSeconds: 180,
      timerLabel: 'Pavo',
    }),
    recipe({
      id: 'pavo-sarten',
      name: 'Pavo salteado con pimiento',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('pavo', '120 g', 120, 'g'), ing('pimiento', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Saltea pavo 4 min, añade pimiento 3 min.', 'Pavo + pimiento.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 420, timerLabel: 'Salteado' }),
      ])],
    }),
    recipe({
      id: 'salmon-plancha-simple',
      name: 'Salmón a la plancha',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'ligero'],
      fodmap: FOD_LOW,
      ingredients: [ing('salmon', '150 g', 150, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('plancha', 'Plancha', ['plancha', 'vitro'], [
        step('cook', L('Piel abajo primero 4 min, vuelta 2-3 min hasta opaco.', 'Salmón plancha 4+3 min.', 'Plancha salmón.'), { termIds: ['sellar'], timerSeconds: 420, timerLabel: 'Salmón' }),
      ])],
    }),
    recipe({
      id: 'salmon-micro',
      name: 'Salmón al microondas',
      timeMinutes: 8,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'ligero'],
      fodmap: FOD_LOW,
      ingredients: [ing('salmon', '150 g', 150, 'g'), ing('sal', 'al gusto')],
      methods: [m('micro', 'Microondas', ['microondas'], [
        step('cook', L(
          'Coloca el salmón en plato apto micro, tapa parcialmente y cocina potencia media 2-3 min hasta opaco por fuera y que se separe en lascas.',
          'Microondas potencia media 2-3 min hasta salmón opaco y lascas fáciles.',
          'Salmón micro 2-3 min potencia media hasta opaco.',
        ), { phaseId: 'cook', timerSeconds: 180, timerLabel: 'Salmón' }),
      ])],
    }),
    recipe({
      id: 'merluza-sarten',
      name: 'Pescado a la sartén',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'ligero'],
      fodmap: FOD_LOW,
      ingredients: [ing('pescado-congelado', '1 filete', 1, 'filete'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Descongela si hace falta. Sartén con aceite: pescado 3-4 min por lado hasta desmenuzar fácil.', 'Pescado 3-4 min/lado.', 'Sartén pescado.'), { timerSeconds: 420, timerLabel: 'Pescado' }),
      ])],
    }),
    recipe({
      id: 'bowl-lechuga-pollo',
      name: 'Bowl de lechuga y pollo',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['ligero', 'completo'],
      fodmap: FOD_LOW,
      ingredients: [ing('lechuga', '1/2 unidad', 0.5, 'unidad'), ing('pollo', '180 g', 180, 'g'), ing('tomate', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Sartén', ['sarten', 'vitro'], [
        step('chicken', L(
          'Saltea pollo en dados en sartén con aceite a fuego medio-alto 8 min removiendo hasta que no quede rosado por dentro y los jugos salgan claros.',
          'Saltea pollo en dados 8 min a fuego medio-alto hasta cocinado por dentro.',
          'Pollo en dados 8 min hasta jugos claros y sin rosado interior.',
        ), { phaseId: 'cook', termIds: ['saltear'], timerSeconds: 480, timerLabel: 'Pollo', heatLevel: 'medio-alto' }),
        step('bowl', L('Lechuga y tomate en bol; pollo encima; aliña al final.', 'Bowl ensalada caliente.', 'Emplatar.')),
      ])],
    }),
    recipe({
      id: 'salteado-ternera-verduras',
      name: 'Salteado de ternera y verduras',
      timeMinutes: 20,
      difficulty: 'avanzada',
      dishRole: 'platoPrincipal',
      pepperTags: ['especial', 'completo'],
      fodmap: FOD_LOW,
      ingredients: [ing('ternera', '180 g', 180, 'g'), ing('verduras-mixtas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Fuego alto: ternera 2 min, verduras 5 min removiendo constante.', 'Salteado ternera-verduras.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 420, timerLabel: 'Salteado' }),
      ])],
    }),
    recipe({
      id: 'hot-dog-simple',
      name: 'Perrito caliente',
      timeMinutes: 10,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('hot-dog', '2 unidades', 2, 'unidad'), ing('pan', '1 bollo', 1, 'unidad')],
      methods: [m('olla', 'Olla', ['olla', 'vitro'], [
        step('boil', L('Hierve agua, cuece salchichas 5 min. Calienta pan.', 'Salchichas 5 min.', 'Hervir.'), { timerSeconds: 300, timerLabel: 'Salchichas' }),
        step('serve', L(
          'Coloca las salchichas en el pan y sirve caliente.',
          'Monta salchichas en el bollo y sirve.',
          'Emplatar perrito caliente en pan.',
        ), { phaseId: 'serve' }),
      ])],
    }),
  );

  // —— Verduras / legumbres ——
  push(
    recipe({
      id: 'garbanzos-tomate',
      name: 'Garbanzos con tomate frito',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'comfort'],
      fodmap: FOD_MOD,
      ingredients: [ing('garbanzos', '1/2 lata', 0.5, 'lata'), ing('tomate-frito', '100 g', 100, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Escurre garbanzos. Saltea con tomate frito 5 min.', 'Garbanzos en tomate 5 min.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 300, timerLabel: 'Garbanzos' }),
      ])],
    }),
    recipe({
      id: 'garbanzos-espinacas',
      name: 'Garbanzos con espinacas',
      timeMinutes: 15,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('garbanzos', '1/2 lata', 0.5, 'lata'), ing('espinacas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Saltea espinacas 2 min, añade garbanzos escurridos 4 min.', 'Espinacas + garbanzos.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 360, timerLabel: 'Salteado' }),
      ])],
    }),
    recipe({
      id: 'lentejas-tomate',
      name: 'Lentejas con tomate frito',
      timeMinutes: 20,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['comfort', 'completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('lentejas', '1/2 lata', 0.5, 'lata'), ing('tomate-frito', '100 g', 100, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Calienta lentejas escurridas con tomate frito 6 min removiendo.', 'Lentejas + tomate 6 min.', 'Salteado.'), { timerSeconds: 360, timerLabel: 'Lentejas' }),
      ])],
    }),
    recipe({
      id: 'guisantes-jamon',
      name: 'Guisantes con jamón',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('guisantes', '1 puñado', 1, 'puñado'), ing('jamon', '2 lonchas', 2, 'loncha'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Saltea guisantes 5 min; añade jamón troceado 2 min.', 'Guisantes + jamón.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 420, timerLabel: 'Guisantes' }),
      ])],
    }),
    recipe({
      id: 'guisantes-huevo',
      name: 'Guisantes con huevo',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('guisantes', '1 puñado', 1, 'puñado'), ing('huevos', '2 unidades', 2, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Saltea guisantes 4 min. Haz huevos revueltos aparte o en hueco; mezcla.', 'Guisantes + revuelto.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 360, timerLabel: 'Guisantes' }),
      ])],
    }),
    recipe({
      id: 'verduras-mixtas-salteado',
      name: 'Verduras mixtas salteadas',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['rapido', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('verduras-mixtas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Sartén aceite caliente: verduras 6-8 min removiendo hasta tiernas.', 'Verduras 6-8 min.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 420, timerLabel: 'Verduras' }),
      ])],
    }),
    recipe({
      id: 'espinacas-ajos-huevo',
      name: 'Espinacas salteadas con huevo',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('espinacas', '1 puñado', 1, 'puñado'), ing('huevos', '2 unidades', 2, 'unidad'), ing('ajo', '1 diente', 1, 'diente'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Ajo en aceite 1 min, espinacas 2 min, huevos revueltos 2 min.', 'Espinacas + revuelto.', 'Salteado.'), { termIds: ['sofreir', 'saltear'], timerSeconds: 300, timerLabel: 'Salteado' }),
      ])],
    }),
    recipe({
      id: 'pimiento-sarten',
      name: 'Pimiento salteado',
      timeMinutes: 10,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['rapido', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('pimiento', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Tiras de pimiento en sartén 6 min a fuego medio-alto.', 'Pimiento 6 min.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 360, timerLabel: 'Pimiento' }),
      ])],
    }),
    recipe({
      id: 'zanahoria-salteada',
      name: 'Zanahoria salteada',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['rapido'],
      fodmap: FOD_LOW,
      ingredients: [ing('zanahoria', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Rodajas finas de zanahoria 8 min con tapa a fuego medio.', 'Zanahoria 8 min.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 510, timerLabel: 'Zanahoria' }),
      ])],
    }),
    recipe({
      id: 'brocoli-ajos',
      name: 'Brócoli salteado con ajo',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['rapido', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('brocoli', '1/2 unidad', 0.5, 'unidad'), ing('ajo', '2 dientes', 2, 'diente'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Ramos de brócoli: blanquea 3 min o saltea con ajo 6 min total.', 'Brócoli + ajo 6 min.', 'Salteado.'), { termIds: ['blanquear', 'saltear'], timerSeconds: 360, timerLabel: 'Brócoli' }),
      ])],
    }),
    recipe({
      id: 'calabacin-tomate',
      name: 'Calabacín con tomate',
      timeMinutes: 15,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('calabacin', '1 unidad', 1, 'unidad'), ing('tomate', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Calabacín en cubos 5 min; añade tomate troceado 4 min.', 'Calabacín + tomate.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 540, timerLabel: 'Verduras' }),
      ])],
    }),
    recipe({
      id: 'calabacin-relleno-simple',
      name: 'Calabacín salteado con huevo',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('calabacin', '1 unidad', 1, 'unidad'), ing('huevos', '2 unidades', 2, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Saltea calabacín cubos 6 min. Bate huevo, vierte encima y cuaja 3 min.', 'Calabacín + huevo cuajado.', 'Tortilla suelta.'), { termIds: ['saltear'], timerSeconds: 540, timerLabel: 'Calabacín' }),
      ])],
    }),
    recipe({
      id: 'pisto-rapido',
      name: 'Pisto rápido de pimiento y calabacín',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'comfort'],
      fodmap: FOD_MOD,
      ingredients: [ing('pimiento', '1/2 unidad', 0.5, 'unidad'), ing('calabacin', '1/2 unidad', 0.5, 'unidad'), ing('tomate-frito', '100 g', 100, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L(
          'Sartén con aceite a fuego medio: saltea pimiento y calabacín en cubos 8 min removiendo. Añade tomate frito y cocina 5 min más hasta verduras tiernas y salsa espesa.',
          'Saltea pimiento y calabacín 8 min; tomate frito 5 min a fuego medio hasta tierno.',
          'Verduras 8 min + tomate 5 min a fuego medio hasta pisto espeso.',
        ), { phaseId: 'cook', termIds: ['sofreir', 'saltear'], timerSeconds: 780, timerLabel: 'Pisto', heatLevel: 'medio' }),
      ])],
    }),
    recipe({
      id: 'patatas-ajos',
      name: 'Patatas salteadas con ajo',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'guarnicion',
      pepperTags: ['comfort'],
      fodmap: FOD_LOW,
      ingredients: [ing('patatas', '2 medianas', 2, 'unidad'), ing('ajo', '2 dientes', 2, 'diente'), ing('aceite', '2 cucharadas', 2, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Patata en cubos pequeños: fríe/saltea 12-15 min tapado a fuego medio; ajo al final 1 min.', 'Patatas 12-15 min + ajo.', 'Patatas.'), { termIds: ['saltear'], timerSeconds: 780, timerLabel: 'Patatas' }),
      ])],
    }),
    recipe({
      id: 'patatas-sartén-huevo',
      name: 'Patatas a la sartén con huevo',
      timeMinutes: 20,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo', 'comfort'],
      fodmap: FOD_LOW,
      ingredients: [ing('patatas', '2 medianas', 2, 'unidad'), ing('huevos', '2 unidades', 2, 'unidad'), ing('aceite', '2 cucharadas', 2, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        // Contenido canónico en src/data/recipeOverrides.ts — placeholder mínimo aquí
        step('potato', L(
          'Patata en rodajas en sartén con aceite ~12 min hasta tiernas (ver override).',
          'Patata ~12 min hasta tierna.',
          'Patata ~12 min al punto.',
        ), { phaseId: 'cook-potato', timerSeconds: 720, timerLabel: 'Patatas', heatLevel: 'medio' }),
        step('egg', L(
          'Huevos encima, tapa ~3 min hasta clara cuajada; servir.',
          'Huevos encima, tapa ~3 min; servir.',
          'Huevos 3 min tapa; servir.',
        ), { phaseId: 'eggs', timerSeconds: 180, timerLabel: 'Huevos', heatLevel: 'medio-bajo' }),
      ])],
    }),
    recipe({
      id: 'patata-micro',
      name: 'Patata al microondas',
      timeMinutes: 8,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['rapido'],
      fodmap: FOD_LOW,
      ingredients: [ing('patatas', '1 mediana', 1, 'unidad'), ing('sal', 'al gusto')],
      methods: [m('micro', 'Microondas', ['microondas'], [
        step('cook', L('Patata lavada, pincha, microondas alta 4-5 min volteando a mitad.', 'Micro patata 4-5 min.', 'Micro.'), { timerSeconds: 300, timerLabel: 'Patata' }),
      ])],
    }),
    recipe({
      id: 'huevos-patata-micro',
      name: 'Huevo y patata exprés',
      timeMinutes: 12,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_LOW,
      ingredients: [ing('huevos', '1 unidad', 1, 'unidad'), ing('patatas', '1 mediana', 1, 'unidad'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Micro + sartén', ['microondas', 'sarten', 'vitro'], [
        step('potato', L('Patata micro 4 min. Corta en rodajas.', 'Patata micro.', 'Patata.')),
        step('egg', L('Fríe huevo en sartén 2 min; sirve con patata.', 'Huevo + patata.', 'Servir.'), { timerSeconds: 120, timerLabel: 'Huevo' }),
      ])],
    }),
    recipe({
      id: 'brocoli-micro-huevo',
      name: 'Brócoli al microondas con huevo',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('brocoli', '1/2 unidad', 0.5, 'unidad'), ing('huevos', '1 unidad', 1, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Micro + sartén', ['microondas', 'sarten', 'vitro'], [
        step('broccoli', L('Brócoli con agua en bol, micro 3 min.', 'Brócoli micro 3 min.', 'Micro.'), { timerSeconds: 180, timerLabel: 'Brócoli' }),
        step('egg', L('Huevo frito o revuelto en sartén 2 min; sirve con brócoli.', 'Huevo + brócoli.', 'Servir.'), { timerSeconds: 120, timerLabel: 'Huevo' }),
      ])],
    }),
    recipe({
      id: 'sopa-verduras-rapida',
      name: 'Caldo de verduras rápido',
      timeMinutes: 15,
      difficulty: 'fácil',
      dishRole: 'entrante',
      pepperTags: ['ligero', 'comfort'],
      fodmap: FOD_MOD,
      ingredients: [ing('verduras-mixtas', '1 puñado', 1, 'puñado'), ing('sal', 'al gusto')],
      methods: [m('olla', 'Olla', ['olla', 'vitro'], [
        step('simmer', L('Olla con agua: verduras 10 min hasta tiernas; tritura si quieres.', 'Caldo verduras 10 min.', 'Hervir.'), { timerSeconds: 620, timerLabel: 'Caldo' }),
      ])],
    }),
    recipe({
      id: 'cuscus-verduras',
      name: 'Cuscús con verduras',
      timeMinutes: 15,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('cuscus', '80 g', 80, 'g'), ing('calabacin', '1/2 unidad', 0.5, 'unidad'), ing('zanahoria', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('combo', 'Bol + sartén', ['sarten', 'vitro'], [
        step('veg', L('Saltea calabacín y zanahoria 6 min.', 'Verduras 6 min.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 360, timerLabel: 'Verduras' }),
        step('cuscus', L('Cuscús en bol: cubre con agua hirviendo igual volumen, tapa 5 min. Mezcla verduras.', 'Hidratar cuscús 5 min.', 'Cuscús.'), { timerSeconds: 300, timerLabel: 'Cuscús', termIds: ['reposar'] }),
      ])],
    }),
    noCook({
      id: 'cuscus-atun',
      name: 'Cuscús con atún',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido', 'completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('cuscus', '80 g', 80, 'g'), ing('atun', '1/2 lata', 0.5, 'lata'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      beginner: 'Hidrata cuscús con agua hirviendo 1:1, tapa 5 min. Escurre atún y mezcla con aceite y sal.',
      intermediate: 'Hidrata cuscús 5 min; mezcla atún escurrido y aceite.',
      advanced: 'Cuscús hidratado con atún, aceite y sal mezclados.',
      step2: {
        b: 'Sirve el cuscús templado en un bol.',
        i: 'Emplata cuscús templado y sirve.',
        a: 'Servir cuscús con atún templado.',
      },
    }),
    recipe({
      id: 'revuelto-espinacas',
      name: 'Revuelto de espinacas',
      timeMinutes: 10,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('espinacas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Esp. 1 min, huevo revuelto 2 min a fuego bajo.', 'Revuelto espinacas.', 'Revuelto.'), { termIds: ['saltear'], timerSeconds: 180, timerLabel: 'Revuelto' }),
      ])],
    }),
    recipe({
      id: 'revuelto-setas-estilo',
      name: 'Revuelto de calabacín',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('calabacin', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Calabacín cubos 4 min; huevos revueltos 2 min.', 'Revuelto calabacín.', 'Revuelto.'), { termIds: ['saltear'], timerSeconds: 360, timerLabel: 'Revuelto' }),
      ])],
    }),
    recipe({
      id: 'tortilla-pimiento',
      name: 'Tortilla de pimiento',
      timeMinutes: 12,
      difficulty: 'fácil',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('huevos', '2 unidades', 2, 'unidad'), ing('pimiento', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Saltea pimiento 4 min; añade huevo batido, cuaja 3 min por lado.', 'Tortilla pimiento.', 'Tortilla.'), { termIds: ['saltear'], timerSeconds: 420, timerLabel: 'Tortilla' }),
      ])],
    }),
    recipe({
      id: 'tortilla-cebolla',
      name: 'Tortilla con cebolla',
      timeMinutes: 15,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('huevos', '3 unidades', 3, 'unidad'), ing('cebolla', '1/2 unidad', 0.5, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('onion', L('Cebolla en juliana a fuego bajo 8 min.', 'Pochar cebolla 8 min.', 'Cebolla.'), { termIds: ['pochar'], timerSeconds: 480, timerLabel: 'Cebolla' }),
        step('egg', L('Huevo batido, mezcla, cuaja 4 min y voltea.', 'Tortilla cebolla.', 'Tortilla.'), { timerSeconds: 240, timerLabel: 'Tortilla' }),
      ])],
    }),
    recipe({
      id: 'sarten-mix-pavo-verdura',
      name: 'Pavo con verduras mixtas',
      timeMinutes: 18,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_MOD,
      ingredients: [ing('pavo', '120 g', 120, 'g'), ing('verduras-mixtas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('sarten', 'Sartén', ['sarten', 'vitro'], [
        step('cook', L('Pavo 4 min, verduras 5 min en la misma sartén.', 'Pavo + verduras.', 'Salteado.'), { termIds: ['saltear'], timerSeconds: 540, timerLabel: 'Salteado' }),
      ])],
    }),
    recipe({
      id: 'queso-plancha-pan',
      name: 'Queso a la plancha con pan',
      timeMinutes: 8,
      difficulty: 'fácil',
      dishRole: 'snack',
      pepperTags: ['rapido'],
      fodmap: FOD_MOD,
      ingredients: [ing('queso', '2 lonchas', 2, 'loncha'), ing('pan', '2 rebanadas', 2, 'rebanada')],
      methods: [m('plancha', 'Plancha', ['plancha', 'vitro'], [
        step('cook', L(
          'Plancha queso 1 min por lado a fuego medio hasta fundir; sirve con pan tostado.',
          'Plancha queso 1 min/lado hasta fundir; acompaña con pan.',
          'Queso a la plancha fundido; servir con pan.',
        ), { phaseId: 'cook', termIds: ['gratinar'], timerSeconds: 120, timerLabel: 'Queso', heatLevel: 'medio' }),
      ])],
    }),
  );

  // —— Electrodomésticos ——
  push(
    recipe({
      id: 'patatas-doradas',
      name: 'Patatas doradas',
      timeMinutes: 25,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['comfort', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('patatas', '2 medianas', 2, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [
        m('air', 'Air Fryer', ['airfryer'], [
          step('prep', L('Gajos de patata con aceite y sal; capa única.', 'Gajos aceite+sal.', 'Prep.')),
          step('cook', L('190 °C, 18 min, agitar a mitad.', 'Air Fryer 18 min.', '190 °C.'), {
            timerSeconds: 1080,
            timerLabel: 'Air Fryer',
            temperatureC: 190,
            similarKey: 'patatas_gajo+airfryer+190C',
          }),
        ], { temperature: '190 °C', timeMinutes: 18 }),
        m('horno', 'Horno', ['horno'], [
          step('prep', L('Gajos en bandeja con aceite y sal.', 'Bandeja gajos.', 'Prep.')),
          step('cook', L('200 °C horno 25-28 min, voltea a mitad.', 'Horno 25 min.', '200 °C.'), { timerSeconds: 1500, timerLabel: 'Horno', temperatureC: 200 }),
        ], { temperature: '200 °C', timeMinutes: 28 }),
        m('sarten', 'Sartén', ['sarten', 'vitro'], [
          step('prep', L(
            'Corta patatas en rodajas o gajos finos; seca ligeramente.',
            'Patata en rodajas o gajos finos; secar.',
            'Rodajas o gajos finos de patata secos.',
          ), { phaseId: 'prep' }),
          step('cook', L('Aceite medio, 15 min removiendo hasta doradas.', 'Sartén 15 min.', 'Freír.'), { timerSeconds: 900, timerLabel: 'Patatas' }),
        ], { timeMinutes: 20 }),
      ],
    }),
    applianceProduct({
      base: {
        id: 'nuggets-caseros-estilo',
        name: 'Nuggets de pollo',
        timeMinutes: 15,
        difficulty: 'fácil',
        dishRole: 'snack',
        pepperTags: ['rapido'],
        fodmap: FOD_MOD,
        ingredients: [ing('nuggets', '1 ración', 1, 'ración')],
      },
      productDesc: 'nuggets congelados',
      methods: [
        ['air', 'Air Fryer', ['airfryer'], 190, 12, 'nuggets+airfryer+190C'],
        ['horno', 'Horno', ['horno'], 200, 18, null],
      ],
    }),
    applianceProduct({
      base: {
        id: 'croquetas-jamon-plato',
        name: 'Croquetas de jamón',
        timeMinutes: 12,
        difficulty: 'fácil',
        dishRole: 'snack',
        pepperTags: ['rapido', 'comfort'],
        fodmap: FOD_MOD,
        ingredients: [ing('croquetas-jamon', '1 ración', 1, 'ración')],
      },
      productDesc: 'croquetas',
      methods: [
        ['air', 'Air Fryer', ['airfryer'], 180, 10, 'croquetas+airfryer+180C'],
        ['horno', 'Horno', ['horno'], 200, 14, null],
        ['freidora', 'Freidora', ['freidora'], null, 5, null],
      ],
    }),
    applianceProduct({
      base: {
        id: 'patatas-fritas-congeladas-plato',
        name: 'Patatas fritas congeladas',
        timeMinutes: 15,
        difficulty: 'fácil',
        dishRole: 'guarnicion',
        pepperTags: ['rapido'],
        fodmap: FOD_MOD,
        ingredients: [ing('patatas-fritas-congeladas', '1 ración', 1, 'ración'), ing('sal', 'al gusto')],
      },
      productDesc: 'patatas fritas congeladas',
      methods: [
        ['air', 'Air Fryer', ['airfryer'], 200, 15, 'patatas_fritas+airfryer+200C'],
        ['horno', 'Horno', ['horno'], 220, 20, null],
        ['sarten', 'Sartén', ['sarten', 'vitro'], null, 12, null],
      ],
    }),
    applianceProduct({
      base: {
        id: 'pizza-congelada-plato',
        name: 'Pizza congelada',
        timeMinutes: 15,
        difficulty: 'fácil',
        dishRole: 'platoPrincipal',
        pepperTags: ['rapido', 'comfort'],
        fodmap: FOD_MOD,
        ingredients: [ing('pizza-congelada', '1 unidad', 1, 'unidad')],
      },
      productDesc: 'pizza congelada',
      methods: [
        ['horno', 'Horno', ['horno'], 210, 15, 'pizza+horno+210C'],
        ['air', 'Air Fryer', ['airfryer'], 180, 9, null],
      ],
    }),
    applianceProduct({
      base: {
        id: 'lasana-preparada-plato',
        name: 'Lasaña preparada',
        timeMinutes: 10,
        difficulty: 'fácil',
        dishRole: 'platoPrincipal',
        pepperTags: ['rapido', 'comfort'],
        fodmap: FOD_MOD,
        ingredients: [ing('lasana-preparada', '1 ración', 1, 'ración')],
      },
      productDesc: 'lasaña',
      methods: [
        ['micro', 'Microondas', ['microondas'], null, 6, null],
        ['horno', 'Horno', ['horno'], 180, 20, null],
      ],
    }),
    applianceProduct({
      base: {
        id: 'empanadillas-plato',
        name: 'Empanadillas',
        timeMinutes: 12,
        difficulty: 'fácil',
        dishRole: 'snack',
        pepperTags: ['rapido'],
        fodmap: FOD_MOD,
        ingredients: [ing('empanadillas', '1 ración', 1, 'ración')],
      },
      productDesc: 'empanadillas',
      methods: [
        ['air', 'Air Fryer', ['airfryer'], 180, 10, null],
        ['horno', 'Horno', ['horno'], 200, 14, null],
        ['sarten', 'Sartén', ['sarten', 'vitro'], null, 7, null],
      ],
    }),
    applianceProduct({
      base: {
        id: 'pescado-horno-air',
        name: 'Pescado congelado',
        timeMinutes: 20,
        difficulty: 'media',
        dishRole: 'platoPrincipal',
        pepperTags: ['completo', 'ligero'],
        fodmap: FOD_MOD,
        ingredients: [ing('pescado-congelado', '1 filete', 1, 'filete'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      },
      productDesc: 'filete de pescado congelado',
      methods: [
        ['horno', 'Horno', ['horno'], 200, 22, 'pescado+horno+200C'],
        ['air', 'Air Fryer', ['airfryer'], 180, 15, null],
      ],
    }),
    applianceProduct({
      base: {
        id: 'pollo-horno-air',
        name: 'Pollo al horno / Air Fryer',
        timeMinutes: 30,
        difficulty: 'media',
        dishRole: 'platoPrincipal',
        pepperTags: ['completo', 'especial'],
        fodmap: FOD_LOW,
        ingredients: [ing('pollo', '180 g', 180, 'g'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      },
      productDesc: 'trozos de pollo sazonados',
      methods: [
        ['horno', 'Horno', ['horno'], 200, 30, 'pollo+horno+200C'],
        ['air', 'Air Fryer', ['airfryer'], 180, 25, 'pollo+airfryer+180C'],
      ],
    }),
    applianceProduct({
      base: {
        id: 'verduras-air-horno',
        name: 'Verduras asadas',
        timeMinutes: 20,
        difficulty: 'fácil',
        dishRole: 'guarnicion',
        pepperTags: ['ligero'],
        fodmap: FOD_MOD,
        ingredients: [ing('verduras-mixtas', '1 puñado', 1, 'puñado'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      },
      productDesc: 'verduras mixtas con aceite',
      methods: [
        ['air', 'Air Fryer', ['airfryer'], 180, 15, 'verduras+airfryer+180C'],
        ['horno', 'Horno', ['horno'], 200, 25, null],
        ['sarten', 'Sartén', ['sarten', 'vitro'], null, 12, null],
      ],
    }),
    recipe({
      id: 'pollo-congelado-air',
      name: 'Pollo congelado en Air Fryer',
      timeMinutes: 25,
      difficulty: 'media',
      dishRole: 'platoPrincipal',
      pepperTags: ['completo'],
      fodmap: FOD_LOW,
      ingredients: [ing('pollo-congelado', '1 pieza', 1, 'pieza'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('air', 'Air Fryer', ['airfryer'], [
        step('prep', L('Unta pollo congelado con aceite y sal.', 'Aceite + sal.', 'Prep.')),
        step('cook', L(
          '180 °C unos 22 min; voltea a mitad; comprueba centro 74 °C o jugos claros sin rosado.',
          'Air Fryer 180 °C ~22 min con volteo a mitad hasta 74 °C internos.',
          '180 °C, 22 min, volteo a mitad; 74 °C internos.',
        ), {
          timerSeconds: 1320,
          timerLabel: 'Pollo congelado',
          temperatureC: 180,
          similarKey: 'pollo_congelado+airfryer+180C',
        }),
      ], { temperature: '180 °C', timeMinutes: 25 })],
    }),
    recipe({
      id: 'pimientos-horno',
      name: 'Pimientos al horno',
      timeMinutes: 25,
      difficulty: 'fácil',
      dishRole: 'guarnicion',
      pepperTags: ['especial', 'ligero'],
      fodmap: FOD_MOD,
      ingredients: [ing('pimiento', '2 unidades', 2, 'unidad'), ing('aceite', '1 cucharada', 1, 'cucharada'), ing('sal', 'al gusto')],
      methods: [m('horno', 'Horno', ['horno'], [
        step('prep', L('Pimientos enteros en bandeja con aceite.', 'Pimientos aceite.', 'Prep.')),
        step('roast', L('200 °C 25 min volteando; piel arrugada y carne tierna.', 'Asar 25 min.', '200 °C.'), { timerSeconds: 1500, timerLabel: 'Pimientos', temperatureC: 200 }),
      ], { temperature: '200 °C', timeMinutes: 25 })],
    }),
  );

  return out;
}
